#!/usr/bin/env python3
"""Build a fresh coupled palette frontier from forced missing-color conflicts.

Given an induced-complete exact graph with a validated proper 5-coloring and a
base prefix, scan the bounded p+d candidate language generated by exact unit
directions from an initial vertex prefix.  A fresh candidate whose *known*
p+d incidences already see four colors is forced to the one missing color (or
becomes even more constrained after exact completion).  If two such candidates
with the same forced missing color are exactly unit-adjacent, adding both kills
the current coloring by coupling alone.

All selected endpoints are then checked exactly against every current vertex
and every other selected endpoint.  The saved graph is therefore induced-
complete provided the input graph is induced-complete.  The result only kills
one supplied coloring; it is not chromatic evidence by itself.
"""
from __future__ import annotations
import argparse, hashlib, json
from collections import Counter, defaultdict
from itertools import combinations, product
from pathlib import Path

from hn_exact import K2, unit_modulus
from hn_palette_center_cegis import neg, pack, semantic_sha
from hn_unconditional_scan import valid_coloring, write_json


def load_graph(path: Path):
    d=json.loads(path.read_text())
    pts=[K2(p['a'],p['b'],p['den']) for p in d['pts']]
    edges=sorted({tuple(map(int,e)) for e in d['edges']})
    assert len(set(pts))==len(pts)
    assert all(0<=u<v<len(pts) for u,v in edges)
    assert all(unit_modulus(pts[u]-pts[v]) for u,v in edges)
    return d,pts,edges


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--graph',type=Path,required=True)
    ap.add_argument('--coloring',type=Path,required=True)
    ap.add_argument('--base-vertices',type=int,required=True)
    ap.add_argument('--direction-vertices',type=int,default=1192)
    ap.add_argument('--max-conflict-edges',type=int,default=0,
                    help='0 means keep every fresh forced-missing conflict edge')
    ap.add_argument('--out-dir',type=Path,required=True)
    a=ap.parse_args(); a.out_dir.mkdir(parents=True,exist_ok=True)

    gd,pts,edges=load_graph(a.graph); n=len(pts); n0=a.base_vertices
    assert 1<=a.direction_vertices<=n0<=n
    s=a.coloring.read_text().strip(); assert len(s)==n and all(ch in '01234' for ch in s)
    colors=list(map(int,s)); assert valid_coloring(colors,n,edges)

    dirs=set()
    for u,v in edges:
        if u<a.direction_vertices and v<a.direction_vertices:
            d=pts[v]-pts[u]; dirs.add(d); dirs.add(neg(d))
    assert dirs and all(unit_modulus(d) for d in dirs)

    pointset=set(pts); masks={}; known_count=Counter()
    for i,p in enumerate(pts[:n0]):
        bit=1<<colors[i]
        for d in dirs:
            x=p+d
            if x in pointset: continue
            masks[x]=masks.get(x,0)|bit
            known_count[x]+=1

    hist=Counter(m.bit_count() for m in masks.values())
    forced=defaultdict(list); direct=[]
    for x,m in masks.items():
        k=m.bit_count()
        if k==5: direct.append(x)
        elif k==4:
            miss=next(c for c in range(5) if not (m>>c)&1)
            forced[miss].append(x)

    conflicts=[]
    for c,xs in forced.items():
        for i,j in combinations(range(len(xs)),2):
            if unit_modulus(xs[i]-xs[j]):
                x,y=xs[i],xs[j]
                score=(known_count[x]+known_count[y],min(known_count[x],known_count[y]))
                conflicts.append((score,c,x,y))
    conflicts.sort(key=lambda z:(-z[0][0],-z[0][1],z[1],z[2].den,tuple(z[2].a),tuple(z[2].b),z[3].den,tuple(z[3].a),tuple(z[3].b)))
    if a.max_conflict_edges>0: conflicts=conflicts[:a.max_conflict_edges]
    assert conflicts, 'no fresh forced-missing conflict edge in bounded language'

    selected=[]; seen=set()
    for _,_,x,y in conflicts:
        for q in (x,y):
            if q not in seen: seen.add(q); selected.append(q)

    # Exact completion for every selected endpoint against the full current graph.
    fullpts=list(pts)+selected; fulledges=set(edges)
    exact_neigh=[]
    for i,x in enumerate(selected):
        vi=n+i; ns=[]
        for j,p in enumerate(pts):
            if unit_modulus(x-p):
                ns.append(j); fulledges.add((j,vi))
        exact_neigh.append(ns)
    selected_edges=[]
    for i,j in combinations(range(len(selected)),2):
        if unit_modulus(selected[i]-selected[j]):
            selected_edges.append((i,j)); fulledges.add((n+i,n+j))

    # Find the minimum-conflict extension of the fixed current coloring.  The
    # selected set is tiny in intended use; exhaustive 5^m is exact.
    m=len(selected); assert m<=10, 'selected endpoint set too large for exact seed enumeration'
    best=None
    for cc in product(range(5),repeat=m):
        bad=0
        for i,ns in enumerate(exact_neigh):
            bad+=sum(colors[v]==cc[i] for v in ns)
        for i,j in selected_edges:
            bad+=cc[i]==cc[j]
        if best is None or bad<best[0]: best=(bad,cc)
    seed=colors+list(best[1])
    bad_edges=[(u,v) for u,v in fulledges if seed[u]==seed[v]]
    assert len(bad_edges)==best[0] and best[0]>0

    outgraph={
      'pts':[pack(p) for p in fullpts], 'edges':[list(e) for e in sorted(fulledges)],
      'construction':'fresh forced-missing-color conflict-edge frontier',
      'base_graph_induced_complete':bool(gd.get('induced_unit_edge_completion_pending') is False),
      'all_added_center_pairs_exactly_checked':True,
      'induced_unit_edge_completion_pending':False,
      'all_saved_edges_exact_unit':True,
    }
    write_json(a.out_dir/'GRAPH.json',outgraph)
    (a.out_dir/'SEED.txt').write_text(''.join(map(str,seed))+'\n')
    recs=[]
    loc={q:i for i,q in enumerate(selected)}
    for score,c,x,y in conflicts:
        recs.append({'forced_color':c,'u_local':loc[x],'v_local':loc[y],
                     'u_point':pack(x),'v_point':pack(y),'u_known_incidences':known_count[x],
                     'v_known_incidences':known_count[y],'score':list(score)})
    out={
      'status':'BUILT_COUPLED_FRONTIER','classification':None,
      'input_vertices':n,'input_edges':len(edges),'base_vertices':n0,
      'direction_vertices':a.direction_vertices,'unit_direction_count':len(dirs),
      'fresh_candidate_count':len(masks),'known_color_count_histogram':dict(sorted(hist.items())),
      'fresh_direct_killers':len(direct),'fresh_forced_singletons':sum(map(len,forced.values())),
      'fresh_conflict_edges_found':len(conflicts),'selected_fresh_endpoints':m,
      'selected_endpoint_internal_edges':len(selected_edges),
      'vertices':len(fullpts),'edges':len(fulledges),
      'fixed_input_coloring_min_extension_conflicts':best[0],
      'seed_conflict_edges':[list(e) for e in bad_edges],
      'semantic_pts_edges_sha256':semantic_sha(fullpts,fulledges),
      'all_added_endpoint_relations_exactly_checked':True,
      'positive_fixed_coloring_conflict_is_evidence':False,
      'conflict_edges':recs,
    }
    write_json(a.out_dir/'FRONTIER.json',out)
    print(json.dumps({k:v for k,v in out.items() if k not in ('seed_conflict_edges','conflict_edges')},indent=2))

if __name__=='__main__': main()
